<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-T3EO6I8" ignored="0" name="Chrome Test" tests="5" failures="3" timestamp="23 Feb 2020 17:29:21 GMT" time="81.446" errors="0">
  <testcase name="InstagramTest" time="8.571" classname="Mytests.SocialMediaTest"/>
  <testcase name="facebookTest" time="13.886" classname="Mytests.SocialMediaTest">
    <failure type="java.lang.AssertionError" message="expected [Facebook - log in or sign up] but found [Facebook – log in or sign up]">
      <![CDATA[java.lang.AssertionError: expected [Facebook - log in or sign up] but found [Facebook – log in or sign up]
at Mytests.SocialMediaTest.facebookTest(SocialMediaTest.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- facebookTest -->
  <testcase name="gmailTest" time="10.174" classname="Mytests.SocialMediaTest"/>
  <testcase name="classicCRMTest" time="7.601" classname="Mytests.ERPTest">
    <failure type="java.lang.AssertionError" message="expected [CRMPRO Login Screen] but found [CRMPRO - CRM software for customer relationship management, sales, and support.]">
      <![CDATA[java.lang.AssertionError: expected [CRMPRO Login Screen] but found [CRMPRO - CRM software for customer relationship management, sales, and support.]
at Mytests.ERPTest.classicCRMTest(ERPTest.java:14)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- classicCRMTest -->
  <testcase name="hubSpotTest" time="2.919" classname="Mytests.ERPTest">
    <failure type="java.lang.AssertionError" message="expected [HubSpot Login] but found [HubSpot | Redirecting...]">
      <![CDATA[java.lang.AssertionError: expected [HubSpot Login] but found [HubSpot | Redirecting...]
at Mytests.ERPTest.hubSpotTest(ERPTest.java:23)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- hubSpotTest -->
</testsuite> <!-- Chrome Test -->
